### ISSUE TITLE
Update for 2019

### ISSUE THREAD

**Issue by tannobit** [Pure-Battlefield/PureSeeder3#11]
@bradrhodes @gsarrica  Is anyone still interested in updating this repo to work with BF4 as it currently exists? Obviously this game is old and the devs here have moved on to shinier things, but there still exists a number of us looking for a solid solution. :) 

I'd be happy to branch and create a pull request if pointed in the right direction on how to implement such a change.

**Comment by bradrhodes** [comment]
I haven't looked at it in a few years.  I don't have any time to work on it myself right now.  Your best bet may just be to fork it to make the changes you want.  I might be able to help you out with some general discussion on how it works, etc but its been so long, I'm not sure I'd be much help with anything very specific.
